import React, { useState } from "react";

function SummaryReport({onClose}){
    const [saved, setSaved] = useState(false); // Control save confirmation tooltip

    const handleSave = () => {//Control successful saving message
        setSaved(true);
        setTimeout(() => {
            setSaved(false)
            onClose()
        }, 2500); // Auto-dismiss after 2.5 seconds
        
    }

    return(
        <div style={styles.modal}>
            {/* Warning message */}
            <div style={styles.warning}>
                This Summary is generated by AI and is for reference only. Please consult a doctor if needed.
            </div>

            {/* Content sections */}
            <div style={styles.section}>
                <h4>1. Overall Symptom Trend</h4>
                <p>[EXAMPLE]</p>
            </div>

            <div style={styles.section}>
                <h4>2. Medication Adherence Analysis</h4>
                <p>[EXAMPLE]</p>
            </div>

            <div style={styles.section}>
                <h4>3. Environmental Triggers and Correlations</h4>
                <p>[EXAMPLE]</p>
            </div>

            <div style={styles.section}>
                <h4>4. Emotional and Lifestyle Insights</h4>
                <p>[EXAMPLE]</p>
            </div>

            <div style={styles.section}>
                <h4>5. Summary Outlook and Suggestions</h4>
                <p>[EXAMPLE]</p>
            </div>

            {/* Two button: Save and Cancel */}
            <div style={styles.buttonRow}>
                <button style={styles.saveBtn} onClick={handleSave}>Save</button>
                <button style={styles.closeBtn} onClick={onClose}>Close</button>
            </div>

            {/* Save message pop up */}
            {saved && (
                <div style={styles.toast}>
                    Successfully Saved to History. You can find it under "View History Report".
                </div>
            )}
        </div>
    )
}
//inline CSS style
const styles = {
    modal:{
        background: "#fff", padding: 24, borderRadius: 12, maxWidth: 600, width: "90%", boxSizing: "border-box", boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
        fontSize: 14, lineHeight: 1.6, position: "relative",
    },
    warning:{
        color: "#b30000", fontWeight: "bold", marginBottom: 16,
    },
    section:{
        marginBottom: 18,
    },
    buttonRow:{
        display: "flex", justifyContent: "space-between", marginTop: 24,
    },
    saveBtn:{
        backgroundColor: "#28a745", color: "white", border: "none", padding: "10px 20px", borderRadius: "8px", cursor: "pointer",
    },
    closeBtn:{
        backgroundColor: "#ccc", border: "none", padding: "10px 20px", borderRadius: "8px", cursor: "pointer",
    },
    toast:{
        position: "absolute", left: 16, bottom: -40, background: "#f5f5f5", border: "1px solid #aaa", padding: "8px 12px", borderRadius: "6px",
        fontSize: 13, boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
    }
}
export default SummaryReport